---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 72958.
--- DateTime: 2022/8/2 17:00
---

-- 获取锁中的线程标识
local id = redis.call('get', KEYS[1])
-- 比较线程标识和锁中的标识是否一致
if (id == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end
-- 不一致就直接返回
return 0